name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        app-name: Lsn1.1_Git_vs19
    - name: Install dependencies
      run: dotnet restore /usr/bin/git/ConApp_Lsn1.1_Git_vs19/ConApp_Lsn1.1_Git_vs19.csproj
    - name: Build
      run: dotnet build /usr/bin/git/ConApp_Lsn1.1_Git_vs19/ConApp_Lsn1.1_Git_vs19.csproj --configuration Release --no-restore
    - name: Unit Test
      run: dotnet test --no-restore --verbosity normal
